export const activities = [
  {
    class: "warrior",
    item: "Go to the gym",
    easy: "30mins",
    med: "1hr",
    hard: "2hrs",
  },
  {
    class: "warrior",
    item: "Go swimming",
    easy: "20mins",
    med: "40mins",
    hard: "1hr",
  },
  {
    class: "warrior",
    item: "Go on a run",
    easy: "1mi",
    med: "5mi",
    hard: "10mi",
  },
  {
    class: "warrior",
    item: "Go on a walk",
    easy: "15min",
    med: "30min",
    hard: "1hr",
  },
  {
    class: "warrior",
    item: "Go walk the dog",
    easy: "15min",
    med: "30min",
    hard: "1hr",
  },
  {
    class: "warrior",
    item: "Play sports with the kids",
    easy: "15min",
    med: "30min",
    hard: "1hr",
  },
  {
    class: "warrior",
    item: "Go play tennis",
    easy: "30mins",
    med: "1hr",
    hard: "2hrs",
  },
  {
    class: "warrior",
    item: "Do pushups",
    easy: 10,
    med: 25,
    hard: 40,
  },
  {
    class: "warrior",
    item: "Do situps",
    easy: 10,
    med: 25,
    hard: 40,
  },
  {
    class: "warrior",
    item: "Lift some at-home weights",
    easy: "15mins",
    med: "30mins",
    hard: "1hr",
  },
  {
    class: "warrior",
    item: "Do some-pull ups",
    easy: 10,
    med: 25,
    hard: 40,
  },
  {
    class: "warrior",
    item: "Go on a hike",
    easy: "",
    med: "",
    hard: "3pts",
  },
  {
    class: "warrior",
    item: "Participate in a marathon",
    easy: "",
    med: "",
    hard: "3pts",
  },
  {
    class: "warrior",
    item: "Ride a bike",
    easy: "15mins",
    med: "30mins",
    hard: "1hr",
  },
  {
    class: "warrior",
    item: "Go to sleep on time",
    easy: "",
    med: "2pts",
    hard: "",
  },
  {
    class: "warrior",
    item: "Wake up and not check your phone immediately",
    easy: "",
    med: "2pts",
    hard: "",
  },
  {
    class: "warrior",
    item: "Go to a kickboxing lesson",
    easy: "",
    med: "2pts",
    hard: "",
  },
  {
    class: "warrior",
    item: "Do some yoga",
    easy: "",
    med: "2pts",
    hard: "",
  },
  {
    class: "warrior",
    item: "Meditate",
    easy: "",
    med: "2pts",
    hard: "",
  },
  {
    class: "warrior",
    item: "Go rock climbing",
    easy: "",
    med: "",
    hard: "3pts",
  },
  {
    class: "",
    item: "",
    easy: "",
    med: "",
    hard: "",
  },
  {
    class: "healer",
    item: "Do the laundry",
    easy: "",
    med: "2pts",
    hard: "",
  },
  {
    class: "healer",
    item: "Do the dishes",
    easy: "1pt",
    med: "",
    hard: "",
  },
  {
    class: "healer",
    item: "Sweep the floor",
    easy: "1pt",
    med: "",
    hard: "",
  },
  {
    class: "healer",
    item: "Mop the floor",
    easy: "",
    med: "2pts",
    hard: "",
  },
  {
    class: "healer",
    item: "Mow the lawn",
    easy: "",
    med: "",
    hard: "3pts",
  },
  {
    class: "healer",
    item: "Wash your car",
    easy: "",
    med: "2pts",
    hard: "",
  },
  {
    class: "healer",
    item: "Do your skincare routine",
    easy: "",
    med: "2pts",
    hard: "",
  },
  {
    class: "healer",
    item: "Restock the fridge",
    easy: "",
    med: "2pts",
    hard: "",
  },
  {
    class: "healer",
    item: "Restock your essentials around the house",
    easy: "",
    med: "2pts",
    hard: "",
  },
  {
    class: "healer",
    item: "Meal prep for the week",
    easy: "",
    med: "",
    hard: "3pts",
  },
  {
    class: "healer",
    item: "Cook breakfast",
    easy: "1pt",
    med: "",
    hard: "",
  },
  {
    class: "healer",
    item: "Cook lunch",
    easy: "1pt",
    med: "",
    hard: "",
  },
  {
    class: "healer",
    item: "Cook dinner",
    easy: "1pt",
    med: "",
    hard: "",
  },
  {
    class: "healer",
    item: "Make a healthy snack",
    easy: "1pt",
    med: "",
    hard: "",
  },
  {
    class: "healer",
    item: "Clean dirty mirrors",
    easy: "1pt",
    med: "",
    hard: "",
  },
  {
    class: "healer",
    item: "Dust the surfaces around the house",
    easy: "1pt",
    med: "",
    hard: "",
  },
  {
    class: "healer",
    item: "Wash the bedsheets and pillowcases",
    easy: "",
    med: "2pts",
    hard: "",
  },
  {
    class: "healer",
    item: "Wash the towels",
    easy: "1pt",
    med: "",
    hard: "",
  },
  {
    class: "healer",
    item: "Attend social events",
    easy: "",
    med: "",
    hard: "3pts",
  },
  {
    class: "healer",
    item: "Call your loved ones",
    easy: "",
    med: "",
    hard: "3pts",
  },
  {
    class: "healer",
    item: "Drink water",
    easy: "1gal",
    med: "2gals",
    hard: "3gals",
  },
  {
    class: "scholar",
    item: "Study",
    easy: "20mins",
    med: "40mins",
    hard: "1hr",
  },
  {
    class: "scholar",
    item: "Read a book fictional",
    easy: "20mins",
    med: "40mins",
    hard: "1hr",
  },
  {
    class: "scholar",
    item: "Learn a new skill",
    easy: "20mins",
    med: "40mins",
    hard: "1hr",
  },
  {
    class: "scholar",
    item: "Think on how you can improve your worth at work",
    easy: "",
    med: "",
    hard: "3pts",
  },
  {
    class: "scholar",
    item: "Research financial literacy",
    easy: "",
    med: "",
    hard: "3pts",
  },
  {
    class: "scholar",
    item: "Learn a new language",
    easy: "",
    med: "2pts",
    hard: "",
  },
  {
    class: "scholar",
    item: "Write a blog post",
    easy: "",
    med: "2pts",
    hard: "",
  },
  {
    class: "scholar",
    item: "Write a journal post about your day",
    easy: "",
    med: "2pts",
    hard: "",
  },
  {
    class: "scholar",
    item: "Read a book that improves your day-to-day life",
    easy: "20mins",
    med: "40mins",
    hard: "1hr",
  },
  {
    class: "scholar",
    item: "Watch/read a motivational speaker/book",
    easy: "20mins",
    med: "40mins",
    hard: "1hr",
  },
  {
    class: "scholar",
    item: "Research about a way to earn money outside of work",
    easy: "",
    med: "",
    hard: "3pts",
  },
  {
    class: "scholar",
    item: "Do a good deed",
    easy: "",
    med: "",
    hard: "3pts",
  },
  {
    class: "scholar",
    item: "Volunteer your time to those in need",
    easy: "15mins",
    med: "30mins",
    hard: "1hr",
  },
  {
    class: "scholar",
    item: "Research new hobbies",
    easy: "",
    med: "2pts",
    hard: "",
  },
  {
    class: "scholar",
    item: "Research places you'd like to travel to",
    easy: "",
    med: "2pts",
    hard: "",
  },
  {
    class: "scholar",
    item: "Create a plan for the future",
    easy: "",
    med: "",
    hard: "3pts",
  },
  {
    class: "scholar",
    item: "Research ways to cut expenses",
    easy: "",
    med: "",
    hard: "3pts",
  },
  {
    class: "scholar",
    item: "Research healthy foods to add into your diet",
    easy: "",
    med: "",
    hard: "3pts",
  },
  {
    class: "scholar",
    item: "Help your kid with their homework",
    easy: "",
    med: "2pts",
    hard: "",
  },
  {
    class: "scholar",
    item: "Cut your screen time down",
    easy: "30mins",
    med: "1hr",
    hard: "2hrs",
  },
];
